export const SITE_CONFIG = {
  name: "M-Wakili AI",
  tagline: "Your Full-Time AI Kenyan Lawyer",
  description: "Specialised AI Agents trained on Kenyan law to help you get work done. Receive instant legal advice, research, drafting, analysis and citations 24 hours a day.",
  url: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  email: "hello@m-wakili.ai",
  social: {
    twitter: "https://x.com/mwakili",
    github: "https://github.com/mwakili",
    linkedin: "https://linkedin.com/company/mwakili",
  },
} as const

export const AGENTS = [
  {
    id: "research",
    name: "AI Research Agent",
    description: "Deep legal research across Kenyan Acts, Constitution, case law, regulations, and Gazette notices",
    icon: "Search",
    color: "from-violet-500 to-purple-600",
    capabilities: [
      "Deep legal research",
      "Searches Kenyan Acts",
      "Constitution analysis",
      "Case law search",
      "Regulations lookup",
      "Gazette Notices",
      "Legal opinions",
    ],
    returns: ["Summary", "Authorities", "Sources", "Citations"],
  },
  {
    id: "drafting",
    name: "Legal Drafting Agent",
    description: "Draft contracts, demand letters, court pleadings, affidavits, and more",
    icon: "FileText",
    color: "from-blue-500 to-cyan-600",
    capabilities: [
      "Contracts",
      "Demand letters",
      "Employment agreements",
      "Court pleadings",
      "Affidavits",
      "Company resolutions",
      "Policies",
    ],
    returns: ["Draft Document", "Legal Review", "Clause Suggestions"],
  },
  {
    id: "case-law",
    name: "Case Law Research Agent",
    description: "Find relevant precedents from Court of Appeal, Supreme Court, and High Court",
    icon: "Scale",
    color: "from-amber-500 to-orange-600",
    capabilities: [
      "Relevant precedents",
      "Court of Appeal decisions",
      "Supreme Court cases",
      "High Court judgments",
      "Relevance scoring",
    ],
    returns: ["Relevance Score", "Judge", "Court", "Year", "Citations"],
  },
  {
    id: "contract-review",
    name: "Contract Review Agent",
    description: "Upload DOCX or PDF for AI-powered contract review and risk analysis",
    icon: "FileSearch",
    color: "from-emerald-500 to-teal-600",
    capabilities: [
      "Risk identification",
      "Missing clauses",
      "Recommendations",
      "Plain English explanation",
    ],
    returns: ["Risk Assessment", "Missing Clauses", "Recommendations"],
  },
  {
    id: "compliance",
    name: "Compliance Agent",
    description: "Business compliance with KRA, NSSF, SHA, Company filings, Employment Act, Tax, AML, Data Protection",
    icon: "Shield",
    color: "from-red-500 to-rose-600",
    capabilities: [
      "KRA compliance",
      "NSSF",
      "SHA",
      "Company filings",
      "Employment Act",
      "Tax",
      "AML",
      "Data Protection",
    ],
    returns: ["Compliance Report", "Deadlines", "Required Actions"],
  },
  {
    id: "employment",
    name: "Employment Law Agent",
    description: "Hiring, termination, disciplinary process, redundancy, leave, benefits, employee rights",
    icon: "Users",
    color: "from-sky-500 to-indigo-600",
    capabilities: [
      "Hiring",
      "Termination",
      "Disciplinary process",
      "Redundancy",
      "Leave",
      "Benefits",
      "Employee rights",
    ],
    returns: ["Legal Advice", "Process Steps", "Document Templates"],
  },
  {
    id: "family",
    name: "Family Law Agent",
    description: "Divorce, custody, succession, marriage, Children Act, inheritance, maintenance",
    icon: "Heart",
    color: "from-pink-500 to-rose-600",
    capabilities: [
      "Divorce",
      "Custody",
      "Succession",
      "Marriage",
      "Children Act",
      "Inheritance",
      "Maintenance",
    ],
    returns: ["Legal Guidance", "Court Process", "Documentation"],
  },
  {
    id: "criminal",
    name: "Criminal Law Agent",
    description: "Charges, procedure, bail, sentencing, rights, police procedure",
    icon: "Gavel",
    color: "from-gray-600 to-slate-800",
    capabilities: [
      "Charges",
      "Procedure",
      "Bail",
      "Sentencing",
      "Rights",
      "Police procedure",
    ],
    returns: ["Case Analysis", "Bail Guidelines", "Defense Strategy"],
  },
  {
    id: "land",
    name: "Land Law Agent",
    description: "Title verification, land disputes, transfers, lease agreements, boundary disputes",
    icon: "Map",
    color: "from-green-500 to-emerald-600",
    capabilities: [
      "Title verification",
      "Land disputes",
      "Transfers",
      "Lease agreements",
      "Boundary disputes",
    ],
    returns: ["Title Report", "Legal Opinion", "Required Documents"],
  },
  {
    id: "immigration",
    name: "Immigration Agent",
    description: "Visa advice, work permits, citizenship, refugee law, permanent residence",
    icon: "Globe",
    color: "from-teal-500 to-cyan-600",
    capabilities: [
      "Visa advice",
      "Work permits",
      "Citizenship",
      "Refugee law",
      "Permanent residence",
    ],
    returns: ["Eligibility Check", "Application Process", "Document Checklist"],
  },
  {
    id: "corporate",
    name: "Business Registration Agent",
    description: "Company registration, NGOs, partnerships, business names, compliance",
    icon: "Building2",
    color: "from-violet-500 to-indigo-600",
    capabilities: [
      "Company registration",
      "NGOs",
      "Partnerships",
      "Business names",
      "Compliance filings",
    ],
    returns: ["Registration Steps", "Required Forms", "Fee Schedule"],
  },
  {
    id: "litigation",
    name: "Litigation Assistant",
    description: "Prepare submissions, organize evidence, timeline generation, witness summaries",
    icon: "Sword",
    color: "from-orange-500 to-red-600",
    capabilities: [
      "Prepare submissions",
      "Organize evidence",
      "Timeline generation",
      "Cross-reference documents",
      "Witness summaries",
    ],
    returns: ["Case Timeline", "Evidence Summary", "Submission Draft"],
  },
] as const

export const PRICING_PLANS = [
  {
    name: "Free",
    price: 0,
    currency: "KES",
    interval: "month",
    description: "Perfect for getting started",
    features: [
      "10 AI questions",
      "Basic legal research",
      "Standard citations",
      "Email support",
    ],
    cta: "Start Free",
    popular: false,
  },
  {
    name: "Professional",
    price: 99900,
    currency: "KES",
    interval: "month",
    description: "For legal professionals",
    features: [
      "Unlimited research",
      "Legal drafting",
      "Document upload",
      "Priority AI access",
      "Export PDF/DOCX",
      "Advanced citations",
    ],
    cta: "Subscribe",
    popular: true,
  },
  {
    name: "Business",
    price: 499900,
    currency: "KES",
    interval: "month",
    description: "For teams and firms",
    features: [
      "Unlimited everything",
      "Team workspace",
      "API access",
      "Collaboration tools",
      "Dedicated support",
      "Custom branding",
    ],
    cta: "Subscribe",
    popular: false,
  },
  {
    name: "Enterprise",
    price: 0,
    currency: "KES",
    interval: "custom",
    description: "For large organizations",
    features: [
      "Custom pricing",
      "SSO & SAML",
      "Private AI agents",
      "Custom integrations",
      "On-premise option",
      "24/7 dedicated support",
    ],
    cta: "Contact Sales",
    popular: false,
  },
] as const

export const STATISTICS = [
  { value: "250,000+", label: "Legal Questions Answered", suffix: "+" },
  { value: "95", label: "Accuracy with Sources", suffix: "%" },
  { value: "24/7", label: "Always Available", suffix: "" },
  { value: "500+", label: "Kenyan Acts & Regulations Indexed", suffix: "+" },
] as const
